# Generated by Django 3.2.6 on 2021-08-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('ap_apartment', models.BigAutoField(primary_key=True, serialize=False)),
                ('ap_descripcion', models.CharField(max_length=50, verbose_name='Description')),
                ('ap_cost_offer', models.CharField(max_length=50, verbose_name='Offer Cost')),
                ('ap_cost_list', models.CharField(max_length=50, verbose_name='List cost')),
                ('ap_is_remodeling', models.BooleanField(verbose_name='Is it remodeling?')),
                ('ap_latitude', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Latitude')),
                ('ap_longitude', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('ci_city', models.BigAutoField(primary_key=True, serialize=False)),
                ('ci_name', models.CharField(max_length=50, verbose_name='Name')),
                ('ci_abbr', models.CharField(max_length=5, verbose_name='Abbreviation')),
                ('ci_url', models.CharField(max_length=80, verbose_name='URL Photo')),
                ('ci_alt', models.CharField(max_length=80, verbose_name='Photo Alternative Text')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('co_country', models.BigAutoField(primary_key=True, serialize=False)),
                ('co_name', models.CharField(max_length=50, verbose_name='Name')),
                ('co_abbr', models.CharField(max_length=5, verbose_name='Abbreviation')),
                ('co_url', models.CharField(max_length=80, verbose_name='URL Photo')),
                ('co_alt', models.CharField(max_length=80, verbose_name='Photo Alternative Text')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('fe_feature', models.BigAutoField(primary_key=True, serialize=False)),
                ('fe_type', models.CharField(max_length=50, verbose_name='Type')),
                ('fe_name', models.CharField(max_length=50, verbose_name='Name')),
                ('fe_icon_url', models.CharField(max_length=80, verbose_name='URL Icon')),
                ('fe_icon_color', models.CharField(max_length=80, verbose_name='Color Icon')),
                ('fe_is_visible', models.BooleanField(default=True, verbose_name='Is it visible?')),
                ('fe_is_card', models.BooleanField(default=True, verbose_name='Is it in a card?')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('fl_flat', models.BigAutoField(primary_key=True, serialize=False)),
                ('fl_url', models.CharField(max_length=80, verbose_name='URL Flat')),
                ('fl_alt', models.CharField(max_length=80, verbose_name='Flat Alternative Text')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('in_investment', models.BigAutoField(primary_key=True, serialize=False)),
                ('in_type', models.CharField(max_length=30, verbose_name='Type')),
                ('in_name', models.CharField(max_length=30, verbose_name='Name')),
                ('in_icon_url', models.CharField(max_length=80, verbose_name='URL Icon')),
                ('in_icon_color', models.CharField(max_length=80, verbose_name='Color Icon')),
                ('in_is_visible', models.BooleanField(default=True, verbose_name='Is it visible?')),
                ('in_is_card', models.BooleanField(default=True, verbose_name='Is it in a card?')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('ne_neighborhood', models.BigAutoField(primary_key=True, serialize=False)),
                ('ne_name', models.CharField(max_length=50, verbose_name='Name')),
                ('ne_abbr', models.CharField(max_length=5, verbose_name='Abbreviation')),
                ('ne_url', models.CharField(max_length=80, verbose_name='URL Photo')),
                ('ne_alt', models.CharField(max_length=80, verbose_name='Photo Alternative Text')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('ph_photo', models.BigAutoField(primary_key=True, serialize=False)),
                ('ph_url', models.CharField(max_length=80, verbose_name='URL Photo')),
                ('ph_alt', models.CharField(max_length=80, verbose_name='Photo Alternative Text')),
            ],
        ),
        migrations.CreateModel(
            name='Pleasantness',
            fields=[
                ('pl_pleasantness', models.BigAutoField(primary_key=True, serialize=False)),
                ('pl_type', models.CharField(max_length=30, verbose_name='Type')),
                ('pl_name', models.CharField(max_length=30, verbose_name='Name')),
                ('pl_icon_url', models.CharField(max_length=80, verbose_name='URL Icon')),
                ('pl_icon_color', models.CharField(max_length=80, verbose_name='Color Icon')),
                ('pl_is_visible', models.BooleanField(default=True, verbose_name='Is it visible?')),
                ('pl_is_card', models.BooleanField(default=True, verbose_name='Is it in a card?')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('st_state', models.BigAutoField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=50, verbose_name='Name')),
                ('st_abbr', models.CharField(max_length=5, verbose_name='Abbreviation')),
                ('st_url', models.CharField(max_length=80, verbose_name='URL Photo')),
                ('st_alt', models.CharField(max_length=80, verbose_name='Photo Alternative Text')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('st_street', models.BigAutoField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=50, verbose_name='Name')),
                ('st_abbr', models.CharField(max_length=5, verbose_name='Abbreviation')),
                ('st_url', models.CharField(max_length=80, verbose_name='URL Photo')),
                ('st_alt', models.CharField(max_length=80, verbose_name='Photo Alternative Text')),
            ],
        ),
    ]
